name:                lab-list-comprehensions
version:             0.1.0.0
github:              "cs141/lab-list-comprehensions"
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           "2022 Alex Dixon"

extra-source-files:
- README.md

description:         This lab covers list comprehensions and range syntax.

dependencies:
- base >= 4.7 && < 5
- containers
- primes

library:
  source-dirs: src

tests:
  lab-list-comprehensions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab-list-comprehensions
    - tasty
    - tasty-reporter-muffled
    - tasty-hunit
    - tasty-quickcheck

