name:                lab-type-classes
version:             0.1.0.0
github:              "cs141/lab-type-classes"
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           "2022 Alex Dixon"

extra-source-files:
- README.md

description:         This lab covers the standard type classes in Haskell and the implementation of custom type classes.

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

tests:
  lab-type-classes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab-type-classes
    - tasty
    - tasty-reporter-muffled
    - tasty-hunit
    - tasty-quickcheck

